spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/netctoss
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  jackson:
    serialization:
      indent_output: true

  redis:
    host: 127.0.0.1
    port: 6379



